// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29.10.2024, 17:52:55
const configMerger = require("/Users/evgeniy/Desktop/dev-new/nuxt-catalog/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/evgeniy/Desktop/dev-new/nuxt-catalog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/plugins/**/*.{js,ts,mjs}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/composables/**/*.{js,ts,mjs}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/utils/**/*.{js,ts,mjs}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/evgeniy/Desktop/dev-new/nuxt-catalog/app.config.{js,ts,mjs}"] } }));

module.exports = config
